-- 데이터베이스 생성 및 사용
USE team09;

DROP TABLE IF EXISTS Bookmark;
DROP TABLE IF EXISTS AirQuality;
DROP TABLE IF EXISTS Temperature;
DROP TABLE IF EXISTS Rain;
DROP TABLE IF EXISTS TravelIndex;
DROP TABLE IF EXISTS WeatherAlert;
DROP TABLE IF EXISTS WeatherStatusDim;
DROP TABLE IF EXISTS Region;
DROP TABLE IF EXISTS DateDim;
